### PR TITLE
RC 0.6.6: Komodo Wallet Rebranding + Coins sync

### PR DESCRIPTION
**Pull request by CharlVS**
This PR brings the project in line with Komodo's rebranding strategy. 
https://komodoplatform.com/en/blog/brand-unification/
image

# Changelog:
- Update brand text references to the new brand.
- Sync coins config files from `KomodoPlatform/coins`. New coins were added, and existing coins were updated.
- Sync coin icon asset files from `KomodoPlatform/coins`.
- Replace old branding assets with rebranded assets.
- Alert the user with a popup when opening the app for the first time about rebranding. Remember if they've dismissed it.
- Show rebranding notice on the news feed page. Will be removed in future update. Or, possibly converted to something reusable.
- Fix app crash caused by invalid API byte.

### CODE REVIEW

**Comment by tonymorony** [comment]
@CharlVS what API library version needs to be used for testing?

**Review by endrilickollari — COMMENTED** [review]
Tested in Redmi A1, Android 12 (Go Edition): 

- Alert pop up: 

 
IMG_20230711_134543

When tap `Official press release` by default is light mode that looks okay, with rebranded changes: 

IMG_20230711_134648

But when tap to change to dark mode, it just darken some buttons and increases the contrast to the screen, which does not looks good. At least background need to be dark and font color white: 

IMG_20230711_134731


- Pop up is shown in Feed: 

  
IMG_20230711_134854


Also everything looks good in renaming and icon changes: 

IMG_20230711_134340

IMG_20230711_134502

**Comment by CharlVS** [comment]
@tonymorony 
> @CharlVS, what API library version needs to be used for testing?

Flutter `2.8.1` with the latest stable release of Komodo API.

**Comment by CharlVS** [comment]
Will add @ca333 as a reviewer after QA approval.

**Comment by CharlVS** [comment]
@yurii-khi Could you please give your review?

**Comment by smk762** [comment]
Branding (logos and wording) looks good.
I was unable to see DOC / MARTY in the activation list tho (I did run ./fetch_coins.sh).

**Comment by kivqa** [comment]
@CharlVS I Tested on iOS 16.4.1. In common branding changes looks correct. 
I saw only one issue. On Starting (loading) screen AtomicDex icon first displayed for a moment and after that it changes for new logo. Some times it looks like gray square picture displayed first after that Komodo wallet icon appears. Cant attach video because screen capture is forbidden

**Comment by kivqa** [comment]
Atomicdex logo on Loadhttps://github.com/KomodoPlatform/komodo-wallet-mobile/assets/130828357/d4b80b27-a406-4ac5-98d8-200823a33366

**Comment by kivqa** [comment]
AtomicDex logo on Load

https://github.com/KomodoPlatform/komodo-wallet-mobile/assets/130828357/44c28ecf-90da-4e11-8ebe-f8335a758762

**Comment by naezith** [comment]
@kivqa Did you try completely removing app data and uninstalling it before installing this new version?

**Review by yurii-khi — APPROVED** [review]
Tested Android build, LGTM

**Comment by CharlVS** [comment]
Thanks @kivqa for reporting the issues. I will get the assets for iOS from the design team.

**Comment by CharlVS** [comment]
@kivqa Can you please take another look at iOS?

**Comment by endrilickollari** [comment]
In my Android 12 (Go Edition) overall looks good. 
No issue with icon when app opens firstly, rebranded icon was okay.

Some new issues: 

- icon in installed apps looks like there is a white background: 
  
IMG_20230718_165924

IMG_20230718_165949


- Also in official press release still this dark mode looks not okay: 

IMG_20230718_170147

**Comment by kivqa** [comment]
@CharlVS I observe 
1. that komodo logo change size on loading without any animation. I cant capture this behavior due screen recording is prohibited in the appm but its easy to reproduce.
2. after app upgrade atomicdex icon app still displayed on  until device reboot or may be some long time waiting. Can we force icon app update? 
image
3. how many times should we display with banner on app start? 
image
I observed it few times. Should I see it until tap on link in the banner?
4. I observe banner over Passcode screen, its really does not look good.

**Comment by CharlVS** [comment]
@endrilickollari @kivqa Please check the app icons and launch screen for iOS and Android.


@kivqa The notice is shown when the user opens the app. The notice is never shown again if the user presses the close icon or opens the press release.

**Comment by endrilickollari** [comment]
> @endrilickollari @kivqa Please check the app icons and launch screen for iOS and Android.
> 
> @kivqa The notice is shown when the user opens the app. The notice is never shown again if the user presses the close icon or opens the press release.

The icons look good now. 

IMG_20230720_193515


IMG_20230720_193554

**Comment by kivqa** [comment]
@CharlVS 
1. logo size still jumping on Loading screen for iOS app

https://github.com/KomodoPlatform/komodo-wallet-mobile/assets/130828357/0ef0a23b-1d17-47e5-b2fd-1e4df9dafedc

2. Official release banner appears after Confirm passcode screen for few seconds. After that Confirm passcode screen displays again. Looks strange

https://github.com/KomodoPlatform/komodo-wallet-mobile/assets/130828357/ed4aa845-2528-4874-9eb6-17fd4349a5d0

**Comment by CharlVS** [comment]
> 1\. logo size still jumping on Loading screen for iOS app

@kivqa thanks for that. I'll create a separate task for these polishes in the next release. It is a bit of a challenge to get the native Android/iOS code splash screens (the first one shown) to transition seamlessly to our universal Flutter code loading screen for all screen sizes of all platforms.



> 2\. on iOS app Official release banner appears after Confirm passcode screen for few seconds. After that Confirm passcode screen displays again. Looks strange

@naezith can you please look at this? In the attached video, the rebranding notice should not be shown until the user has completed the sign-up process. 



> 3\. on iOS app some times after user click official release and come back to app. Banner displays over passcode screen

@kivqa this is working as expected.

**Comment by naezith** [comment]
> > 2. on iOS app Official release banner appears after Confirm passcode screen for few seconds. After that Confirm passcode screen displays again. Looks strange
> 
> @naezith can you please look at this? In the attached video, the rebranding notice should not be shown until the user has completed the sign-up process.

`CoinsPage`'s `initState()` opens the dialog at the moment. @CharlVS 

```
  void initState() {
    _scrollController = ScrollController();
    _scrollController.addListener(_scrollListener);
    if (mmSe.running) coinsBloc.updateCoinBalances();

    // Schedule the dialog to show after the current frame
    SchedulerBinding.instance.addPostFrameCallback((_) async {
      final rebrandingNotifier =
          Provider.of<RebrandingProvider>(context, listen: false);

      // Wait for the prefs to load
      await rebrandingNotifier.prefsLoaded;

      if (!rebrandingNotifier.closedPermanently &&
          !rebrandingNotifier.closedThisSession) {
        showRebrandingDialog(context);
      }
    });

    super.initState();
  }
```

I'll check how else we can do it.

**Comment by naezith** [comment]
This change should solve it: https://github.com/naezith/komodo-wallet-mobile/commit/16751112ac453c915da2c3675d7fe3d4912c9d1a

@CharlVS

**Review by smk762 — APPROVED** [review]
No critical defects or regression detected

**Comment by kivqa** [comment]
@CharlVS 
1. 
Issue 2 is still reproducible:
on iOS app Official release banner appears after Confirm passcode screen for few seconds. After that Confirm passcode screen displays again. 
Can you check on your devices? 

2. 
Screen became in white when I tap faucet button for Rick

https://github.com/KomodoPlatform/komodo-wallet-mobile/assets/130828357/ab8d7e0e-29ee-4e8d-b865-a6756a2cfea3

**Comment by kivqa** [comment]
@CharlVS same behavior for faucet on Android Pixel 5 Android 13.
No new branding issues on Android were observed

**Comment by CharlVS** [comment]
@kivqa Please create a new issue with the problems you've described, including steps to reproduce. Please approve this PR if there are no significant issues and it meets the standard for public release.

**Comment by CharlVS** [comment]
@ca333 after merging in, please rebase/merge with `dev`. Note that the way I've done isn't in line with the org's prescribed org's PR protocols where individual features should be merged into `dev` and then RC PRs into `main`.

**Review by kivqa — APPROVED** [review]
Approved. 
I will create separate issue for observed issues.

**Review by ca333 — APPROVED** [review]

**Pull request merged**
