### PR TITLE
[RC] 0.8.0: UI revamp, bug fixes and coins update

### PR DESCRIPTION
**Pull request by CharlVS**
# 0.8.0 Release Notes:
The release 0.8.0 brings forward a myriad of enhancements, bug fixes, localisation updates (big portion of diff) and UI tweaks aimed to improve ZHTLC/general user experience, ensure consistent performance, and maintain the app's stability. Major changes include fixes related to the ZHTLC feature, runtime coin updates, error handling and UI changes, particularly in portfolio page, transaction lists and coin info page. There have also been significant enhancements to ZHTLC enhancing its robustness, responsiveness, and user feedback mechanisms (e.g. animations). Additionally, this release ensures the app's compatibility for building with the latest iOS SDK.

# Changelog:

## Enhancements:
- (9adb38d5) **Runtime Configurations**: Updated coin configurations dynamically. The branch name is configurable.
- (858bf5bc) **Coin Updates**: Updated coin config files and icons from KomodoPlatform/coins master branch.
- (899767e9) **Coin Info**: Streamlined coin info page header buttons.
- (f95eb123) **Transaction UI**: Introduced transaction list scroll bar.
- (764a69c8, 98f5727d) **UI Improvements**: Enhanced Tx send/receive icon sizes and contrast for tx addresses and notes.
- (9fd55c1c) **Transaction UI**: Simplified transactions list items.
- (856e272c) **UI Refactoring**: Moved widget for animated collapse (shown when ZHTLC progress banner appears and disappears) to its own file with other improvements.
- (028c44e2) **Button Feature**: Created a re-usable eager-loading button to hide the loading status of the "add coins" button.
- (7f374598) **UI Animations**: Animated ZHTLC activation progress bar.
- (f062bebc) **Framework Update**: Upgraded minimum required Dart version - Flutter version remains unchanged.
- (4ca324cc) **UI Refinement**: Fixed iOS warning text style and reorganized form order.
- (bbb82f9d) **UI Tweaks**: Adjusted coin icons on the portfolio page to display better.
- (c995be92) **Portfolio Page Improvements**: Simplified the portfolio page layout and assets proportion graph. Now 2x or more coins fit in the same height without any lost information.
- (796d9920) **Asset Graph**: Tweaks to the animated asset proportion graph.  The assets proportion graph animates changes in real-time.
- (9cb39de4, d0d73525) **Add Coin Button**: Simplify "ADD COIN" button into a floating action button.

## Bug Fixes:
- (5cb7872f) **Coin Update**: Modified coin updater to run on every app start.
- (53d67add) **UI Fixes**: Addressed issues with shadows on overflowed button text.
- (479ae66b) **Withdrawal Form**: Fixed the withdrawal form malfunction.
- (2e442933, 27e53206) **Error Handling**: Improved CEX error handling and introduced UI tweaks. This reduces the number of exceptions thrown and makes it easier to debug with all exception breakpoints enabled
- (7fbe5493) **Transaction List**: Fixed issues with v2 transactions and ZHTLC pagination and implemented missing pagination for v2.
- (f330a596) **UI Fixes**: Resolved infinite loader issue for "Add coins" button.
- (f15ee19a) **Coin Activation**: Fixed issue where disabled Z coins would be re-activated on launch.
- (c6d3c0f8, 88a0cd7d, 50f01a9a) **ZHTLC**: Addressed various issues including progress dialog delays and incorrect progress displays.
- (557ed0d6) **ZHTLC**: Tweaked ZHTLC resync logic to fix an iOS-related error.
- (c6ff68e4, fedad068, 8b2e182a, 02ce3037) **ZHTLC Resync**: Various improvements and bug fixes.
- (5c744c25, bf94d7f1, ea57671d, 2bf0b853) **iOS 17 & Xcode**: Addressed build errors and updated dependencies for iOS 17 compatibility.
- (1e9cad79) **ZHTLC Dialog**: Ensured that the ZHTLC activation dialog closes upon completion.
- (f61e5d31) **ZHTLC Activation**: Fixed a bug in multi-coin activation progress calculation.

## Miscellaneous:
- (575ada3b, 76cea285) **Version Bumping**: Adjusted the release version.
- (414ed51a) **Repo Management**: Merged `master` branch into `dev`.
- (f6851835) **Settings**: Removed ZHTLC status from the settings list. No longer needed as the status of ZHTLC is automatically polled without user needing to prompt UI.
- (5bb00db8) **UI**: Modified the rotating progress indicator to be more in line with Google's design.
- (c9776469) **Refactoring**: Codebase improvements related to transaction loading.
- (628798b8) **ZHTLC**: Introduced minor bug fixes related to ZHTLC.
- (2c3a6a4d) **Rebranding**: Added expiration to rebranding notice.
- (????????) **Misc**: ZHTLC Easter for @smk762 (only in debug mode)
- (8c3eab4d) **ZHTLC**: Tweaked activation ETA calculation to be less volatile. The accuracy of the ETA is beyond our control. It's more of a perceived UX improvement than an actual tool.
- (53e7ed4f, ec76b221) **Code Cleanup**: Formatted code and removed unused parts.
- (baeaa6e1) **ZHTLC**: Silenced ZHTLC progress notifications.
- (74fb0beb) **Error Handling**: Minor bug fixes and improved error handling.
- (879c7587) **Docs**: Fixed documentation for [AnimatedAssetProportionsBarGraph].

Note: The commits made by @naezith are mainly focused on the ZHTLC functionality and its related cleanups and fixes.

# Misc notes:
- Test with Komodo Defi Framework API build: `e9559c2290f0f81c56455e05e1d478ba675dc03a`

# Suggested "To Test" List for QA:
@kivqa may have already tested many of these items from their individual PR(s).

1. **Coin Update Mechanism**:
    - Ensure that the coin update runs every time the app is launched. (Shown in logs)
    - Check if the downloaded update takes effect from the next app launch.

2. **Coin Configurations**:
    - Verify if the coin configurations can be updated during runtime. Downloaded changes will only take effect from the next launch.
    - Check the bundled updated coin config files and icons for consistency. The updater will not fetch missing coin icons for new coins added in the future.

3. **Transaction Lists & UI**:
    - Verify the updated transaction list items.
    - Validate that more than 10 transactions show up on the coins page when scrolled to the bottom.
    - Ensure the visibility and functionality of the transaction list scroll bar.

4. **Coin Info Pages**:
    - Review the updated coin info page header buttons.
    - Test the "Send", "Receive", "Faucet" and "Claim" buttons for functionality.

5. **ZHTLC Feature**:
    - Test the ZHTLC progress dialog to ensure it opens without delay when tapped in the early stage of activation.
    - Confirm that the ZHTLC progress does not always show 100% when resuming sync for an interrupted initial sync.
    - Ensure that the ZHTLC resyncs on iOS when minimized and re-opened.
    - Ensure `ARRR` is only cancellable on initial activation.
    - Ensure sapling activation mode only shows if test coins are enabled.

6. **UX Tweaks**:
    - Ensure the correct working of the rotating progress indicator.
    - Validate the coin icon presentation, especially for square icons like PANDA.

7. **Bug Fixes**:
    - Verify the withdraw form functionality.
    - Confirm that the "Add Coins" button doesn't show an infinite loader.
    - Check the ZHTLC dialog's localizations are present in a non-English language.

8. **Compatibility & Version Updates**:
    - Test the app on the latest iOS version (iOS 17) and ensure no build errors.
    - Check if the app runs smoothly on Flutter `2.8.1`. I'm referencing APIs not compatible with the lower-bound of the Dart versions which Flutter `2.8.1` supports. I've put build-time (pubspec `sdk` field and runtime (`main.dart`) checks, but the VS Code linter still showed warnings about this.

9. **Miscellaneous**:
    - Test the functionality of the animated asset proportion graph.
    - Confirm that the "Add Coin" button has been simplified into a Floating Action Button (FAB) and functions properly.
    - Check the updated portfolio page and ensure more coins fit and display correctly.

Feel free to suggest any changes to changelog notes or suggested tests.

### CODE REVIEW

**Comment by smk762** [comment]
So far most things look ok, but I've had a couple of periods where spinner was up for longer than expected. 


https://github.com/KomodoPlatform/komodo-wallet-mobile/assets/35845239/835a9e22-d68b-45c0-baeb-809d3e151d95

A few things seen in logs which might need further investigation:
```
13:24:26.494 setting_page:723] Converting object to an encodable object failed: Closure: () => Map<String, dynamic> from Function 'ryb':.
Error saving swaps for log export: Converting object to an encodable object failed: Closure: () => Map<String, dynamic> from Function 'ryb':.
```

```

13:24:32.637 getBalance] Error getting ARRR balance
13:24:32.637 coins_bloc:458] Error getting ARRR balance
13:24:32.638 notif_service] show] PlatformException(error, com.komodoplatform.atomicdex: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., null, java.lang.IllegalArgumentException: com.komodoplatform.atomicdex: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:491)
	at android.app.PendingIntent.getActivity(PendingIntent.java:477)
	at android.app.PendingIntent.getActivity(PendingIntent.java:441)
	at com.komodoplatform.atomicdex.MainActivity.createNotification(MainActivity.java:119)
	at com.komodoplatform.atomicdex.MainActivity$1.onMethodCall(MainActivity.java:146)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:206)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
)
```

```
13:51:17.858 coins_bloc:244] NoSuchMethodError: The setter 'QSe=' was called on null.
Receiver: null
Tried calling: QSe=
```

**Comment by kivqa** [comment]
```
13:51:17.858 coins_bloc:244] NoSuchMethodError: The setter 'QSe=' was called on null.
Receiver: null
Tried calling: QSe=
```
Possible steps to raise this error:
1. Import wallet and activate ARRR. Wait until activaion completed
2. Restart app. Wait until ZHTLC coin activation message displayed but not completed. Open ARRR coin

**Comment by kivqa** [comment]
I was not able to reproduce issue with long delays on Claim and Dex screen.ARRR balance issue was not reproduced on my setup as well.  Probably issue on internet connection

**Review by ca333 — APPROVED** [review]
secure code reviewed

**Comment by kivqa** [comment]
Compatibility tests results:
Android 14 - ok, no issues
Android 13 - ok, no issues
Android 11 - ok, no issues
Android 10 - ok, no issues
Android 9 - ok, no issues
Android 8.1 - ok, no issues
Android 7 - app could be installed and launched, works unstable and crashes
Android 6 - installation impossible

**Comment by smk762** [comment]
> I was not able to reproduce issue with long delays on Claim and Dex screen.ARRR balance issue was not reproduced on my setup as well. Probably issue on internet connection

A distinct possibility, you can see the low bars in my video

**Comment by smk762** [comment]
I'm not sure exactly what's happening here

https://github.com/KomodoPlatform/komodo-wallet-mobile/assets/35845239/a24b235a-39dd-4c5e-8225-1772c55ca7b9

Is it re-activating ARRR? Is ARRR actually still active from before, but it's trying again just in case?

In logs:
```
15:26:00.560 mm:_logRes] [getTransactions] MM Response logged. Body: {"mmrpc":"2.0","error":"Invalid column type Null at index: 2, name: block","error_path":"z_coin","error_trace":"z_coin:714] z_coin:582]","error_type":"StorageError","error_data":"Invalid column type Null at index: 2, name: block","id":null}
```
I've seen this in legacy desktop and cli tests in the past, though process seems to recover later. (cc: @borngraced )

@CharlVS maybe we can use https://developers.komodoplatform.com/basic-docs/atomicdex-api-legacy/get_enabled_coins.html to confirm if activation is required?

**Comment by CharlVS** [comment]
@smk762 @kivqa Please test my fixes for the following issues mentioned:
 - [x] Fixed private key dialog showing infinite loader. 
 - [x] Additional checks in place not to resync ZHTLC that are already activated.
 - [x] Bump minimum Android version to `8.1` as per failed testing on older Android versions.
 - [x] Swaps error showing when exporting logs. I successfully reproduced it while I had an ongoing swap. Didn't test before fix with no ongoing swaps.
 - [x] Notifications error from swap notification.
 
 MAYBE FIXED:
 - [ ] @kivqa error in logs reported [here](https://github.com/KomodoPlatform/komodo-wallet-mobile/pull/78#issuecomment-1768363806). I couldn't reproduce it and the error message shared doesn't give enough info to determine the specific line causing it, but I've done some refactoring that may prevent it.
 
 And additionally, I found another issue which I've fixed:
- [x] ZHTLC progress bar not animating.

**Comment by borngraced** [comment]
> I'm not sure exactly what's happening here
> Screen_Recording_20231019_152727.mp4
> 
> Is it re-activating ARRR? Is ARRR actually still active from before, but it's trying again just in case?
> 
> In logs:
> 
> ```
> 15:26:00.560 mm:_logRes] [getTransactions] MM Response logged. Body: {"mmrpc":"2.0","error":"Invalid column type Null at index: 2, name: block","error_path":"z_coin","error_trace":"z_coin:714] z_coin:582]","error_type":"StorageError","error_data":"Invalid column type Null at index: 2, name: block","id":null}
> ```
> 
> I've seen this in legacy desktop and cli tests in the past, though process seems to recover later. (cc: @borngraced )
> 
> @CharlVS maybe we can use https://developers.komodoplatform.com/basic-docs/atomicdex-api-legacy/get_enabled_coins.html to confirm if activation is required?

thanks for the signal, I'm going to try to reproduce this bug when I have some time and work on it.

**Review by kivqa — APPROVED** [review]
Approved. 
- logs does not contains errors,
- notifications are displayed as expected,
- PKs are shown, 
- minimal Android version version bumped up to 8.1 ,
- no errors on swap history exporting, 
- no new issues on ZHLTC activation

**Comment by kivqa** [comment]
>@kivqa error in logs reported https://github.com/KomodoPlatform/komodo-wallet-mobile/pull/78#issuecomment->1768363806. I couldn't reproduce it and the error message shared doesn't give enough info to determine the specific line >causing it, but I've done some refactoring that may prevent it.`

@CharlVS  Its not reproduced anymore. thanks for fix

**Review by smk762 — APPROVED** [review]
Review feedback issues resolved, thanks!

**Pull request merged**
