### PR TITLE
[RC] `0.9.1`: Chart & Order Book Fixes + Sync assets

### PR DESCRIPTION
**Pull request by CharlVS**
# `0.9.1` Release Candidate PR

Various bug fixes and minor improvements relating to advanced view order book and candlestick chart.

Outstanding TODO:
- [x] (#122) Sync coin assets
- [x] (#122) Bump version
- [x] Full changelog
- [x] ~~Maintainer pre-review of changed dependencies~~ (N/A)
- [x] ~~Security team review of changed dependencies~~ (N/A)

# Project changelog:
- Migrate candlestick chart data to Binance's API.
- Prepare for `VOTE2024` release by adding icon asset. Coin will be pushed to app at runtime when coins repo is updated.
- Fix interaction bugs for the candlestick chart and improve performance.
- Migrate legacy order books endpoint to `v2` endpoint.
- Fix bug with incorrect values shown in the advanced trading view.
- Fix QR code scanning bug causing addresses to be improperly parsed.

# Dependency changelog & review:
Not applicable (no changes)

### CODE REVIEW

**Comment by smk762** [comment]
It all looks good, except for a couple of screens which I end up with an endless spinner.
- DEX > Advanced orderbook (sighted once, 3 times after it just spins)
- Markets > Orderbook.

Simple dex orderbook is fine, so it doesnt seem to be a connectivity issue. Logs only have one error including the string "orderbook" - `{"mmrpc":"2.0","error":"BaseRelSameOrderbookTickersAndProtocols","error_path":"orderbook_rpc","error_trace":"orderbook_rpc:250]","error_type":"BaseRelSameOrderbookTickersAndProtocols","id":null}`.

By disabling any coins with a legacy/segwit variant (or only having one of the variants active), these pages load ok.

**Comment by CharlVS** [comment]
@smk762 I've merged the fix for the bug you mentioned. I would appreciate it if you or one of your team members could still create an issue with steps/conditions to reproduce the long loading times you reported.

**Comment by AndrewDelaney** [comment]
I have created the associated issue regarding the orderbook spinner [here](https://github.com/KomodoPlatform/komodo-wallet-mobile/issues/126)

**Review by ca333 — APPROVED** [review]
secure code reviewed

**Pull request merged**
