### PR TITLE
ZHTLC release localization

### PR DESCRIPTION
**Pull request by naezith**
Added the same texts that other protocols have.

### CODE REVIEW

**Comment by naezith** [comment]
I placed the localization keys everywhere I could find except within `z_coin_activation_bloc.dart` since there is no `context` to access the localization. 

Now I need to add them to the intl and messages files for every language.

**Comment by naezith** [comment]
Requires arb & messages files regeneration and 32 new sentences should be translated.

The commit gets quite dirty at regeneration if the formatting differs from the last generation.

ChatGPT can be used for it: https://chat.openai.com/share/5c9106d6-d341-46ad-9a28-39acc351d9cc

**Comment by naezith** [comment]
Added 6 more sentences, Zcoin Bloc is now localized. 

I think there is only one left: `ZCoinProgressNotifications`

The problem with this one is, it does not have access to the `context`. And the place where `ZCoinProgressNotifications.initNotifications();` is called also does not have the `context`.

I'll leave this for now because I can't see a clean solution, as we don't want to carry the localization or the context stuff through the Bloc.

**Comment by naezith** [comment]
The newer branch here: https://github.com/KomodoPlatform/komodo-wallet-mobile/compare/add_arrr...naezith:atomicdex-mobile:regen-localization

**Comment by CharlVS** [comment]
Merged in with `ARRR` release branch.

**Pull request closed without merging**
