### PR TITLE
Sync v0.9.0 dev into piratedex

### PR DESCRIPTION
**Pull request by takenagain**
Rebrands the following items to match Pirate branding

- iOS and Android icons
- In-App logos
- Adds ARRR-BEP20 to the default coins list
- Activates ARRR on first launch via the ZHTLC coin activation flow
- Links from komodoplatform.com to [piratechain.com](https://piratechain.com/)
- RPC port to 7767
- Social media and support links to [piratechain.com/discord](https://piratechain.com/discord)

Logos and Symbols were obtained from [Pirate Network mediakit](https://github.com/PirateNetwork/mediakit)

Sync changes from dev: 
- #103 
- #110

### CODE REVIEW

**Review by kivqa — APPROVED** [review]
Approved.
Checked on iOS and Android:
1. icons and references are correct
2. ZHTLC activation dialog appears as expected on wallet create/import
3. ZHTLC Activation interruption  handled as expected
4. Default coins ARRR and ARRR-BEP20 added

**Review by CharlVS — APPROVED** [review]
Thanks a lot for the contributions. Overall, a good approach to add auto `ARRR` while working with what we have and keeping it as simple as possible.

**Review by smk762 — APPROVED** [review]
Functions as expected for activation & incoming / outgoing swaps / transactions.
ToS etc updated to target as expected. 
Zombie faucet functions as expected. 
Awaiting logo change, but otherwise lgtm!

Minor cosmetic change: instead of "getting transaction" when initiating a withdraw, "generating transaction" or "creating transaction" would be more accurate. The former implies transaction exists and is being grabbed from history.

**Comment by kivqa** [comment]
@takenagain we need to update logo for mobile app (requirement of Pirate): https://github.com/PirateNetwork/mediakit/blob/main/Coin/SVG/Pirate_Logo_Coin_Gold.svg

**Pull request merged**
